// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU0eJ6w4gnGadCLE5rJzCOoyzuvM2uNNE',
    appId: '1:41271625266:android:bb925425bd769abb9f9e2b',
    messagingSenderId: '41271625266',
    projectId: 'notebook-ndabagenga255',
    databaseURL: 'https://notebook-ndabagenga255-default-rtdb.firebaseio.com',
    storageBucket: 'notebook-ndabagenga255.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl-ap8J8U3onjTq15gvenZgzysP8ZVHMg',
    appId: '1:41271625266:ios:b0c7b8e5b8afa2ac9f9e2b',
    messagingSenderId: '41271625266',
    projectId: 'notebook-ndabagenga255',
    databaseURL: 'https://notebook-ndabagenga255-default-rtdb.firebaseio.com',
    storageBucket: 'notebook-ndabagenga255.firebasestorage.app',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCc4gL9He-g4xZYkyJ9KDiZep9QTlCLhc',
    appId: '1:41271625266:web:76fb39f8b57e53fe9f9e2b',
    messagingSenderId: '41271625266',
    projectId: 'notebook-ndabagenga255',
    authDomain: 'notebook-ndabagenga255.firebaseapp.com',
    databaseURL: 'https://notebook-ndabagenga255-default-rtdb.firebaseio.com',
    storageBucket: 'notebook-ndabagenga255.firebasestorage.app',
    measurementId: 'G-8RH1T8HG22',
  );
}
